// src/lib/steps/TeilnehmerStep.svelte
<script lang="ts">
  import Handsontable from 'handsontable/base';
  import { registerAllModules } from 'handsontable/registry';
  import { onMount } from 'svelte';
  import { wizard } from '../store/wizardStore';
  import type { ExamParticipant, FieldErrors } from '../types';

  registerAllModules();

  let gridElement: HTMLDivElement | null = null;
  let hotTable: Handsontable | null = null;
  let isSyncingGrid = false;

  $: tasks = $wizard.data.aufgaben.tasks;
  $: participants = $wizard.data.teilnehmer.participants;
  $: step = $wizard.steps.find((item) => item.id === 'teilnehmer');
  $: errors = $wizard.validation.errorsByStep.teilnehmer;
  $: showErrors = Boolean(step?.touched);
  $: validationMessages = collectValidationMessages(errors);
  $: gridRevision = JSON.stringify({
    tasks,
    participants,
    errors,
    showErrors
  });

  $: if (hotTable && gridRevision) {
    updateGrid();
  }

  function createParticipant(index = participants.length): ExamParticipant {
    return {
      name: `Teilnehmer ${index + 1}`,
      pointsByTask: tasks.map(() => 0)
    };
  }

  function createGridData(): (string | number | null)[][] {
    const rows = participants.map((participant) => [
      participant.name,
      ...tasks.map((_, taskIndex) => participant.pointsByTask[taskIndex] ?? 0)
    ]);

    if (rows.length === 0) {
      const participant = createParticipant(0);

      return [[participant.name, ...participant.pointsByTask]];
    }

    return rows;
  }

  function createColumnHeaders(): string[] {
    return [
      'Teilnehmer',
      ...tasks.map((task, index) => {
        const name = task.name.trim() || `Aufgabe ${index + 1}`;
        const maxPoints = task.maxPoints ?? 0;

        return `${name} (${maxPoints} P.)`;
      })
    ];
  }

  function createColumns() {
    return [
      {
        type: 'text'
      },
      ...tasks.map(() => ({
        type: 'numeric',
        allowInvalid: true
      }))
    ];
  }

  function normalizeText(value: unknown): string {
    if (typeof value === 'string') {
      return value;
    }

    if (value === null || value === undefined) {
      return '';
    }

    return String(value);
  }

  function normalizePoints(value: unknown): number | null {
    if (value === null || value === undefined || value === '') {
      return null;
    }

    if (typeof value === 'number') {
      return Number.isFinite(value) ? value : null;
    }

    const normalized = String(value).trim().replace(',', '.');

    if (!normalized) {
      return null;
    }

    const parsed = Number(normalized);

    return Number.isFinite(parsed) ? parsed : null;
  }

  function readGridParticipants(): ExamParticipant[] {
    if (!hotTable) {
      return [];
    }

    return hotTable
      .getData()
      .map((row) => ({
        name: normalizeText(row[0]).trim(),
        pointsByTask: tasks.map((_, taskIndex) => normalizePoints(row[taskIndex + 1]))
      }))
      .filter(
        (participant) =>
          participant.name.length > 0 || participant.pointsByTask.some((points) => points !== null)
      );
  }

  function syncFromGrid(): void {
    if (!hotTable || isSyncingGrid) {
      return;
    }

    const nextParticipants = readGridParticipants();

    wizard.updateData((current) => ({
      ...current,
      teilnehmer: {
        participants: nextParticipants.length > 0 ? nextParticipants : [createParticipant(0)]
      }
    }));
    wizard.markCurrentTouched();
  }

  function addParticipant(): void {
    wizard.updateData((current) => ({
      ...current,
      teilnehmer: {
        participants: [
          ...current.teilnehmer.participants,
          {
            name: `Teilnehmer ${current.teilnehmer.participants.length + 1}`,
            pointsByTask: current.aufgaben.tasks.map(() => 0)
          }
        ]
      }
    }));
    wizard.markCurrentTouched();
  }

  function hasCellError(row: number, column: number): boolean {
    if (!showErrors) {
      return false;
    }

    if (participants.length === 0) {
      return row === 0 && column === 0 && Boolean(errors.participants?.length);
    }

    if (!participants[row]) {
      return false;
    }

    const field =
      column === 0 ? `participants.${row}.name` : `participants.${row}.pointsByTask.${column - 1}`;

    return Boolean(errors[field]?.length);
  }

  function createCellSettings(row: number, column: number) {
    return {
      className: hasCellError(row, column) ? 'teilnehmer-grid-error' : ''
    };
  }

  function updateGrid(): void {
    if (!hotTable) {
      return;
    }

    isSyncingGrid = true;
    hotTable.updateSettings({
      colHeaders: createColumnHeaders(),
      columns: createColumns(),
      cells: createCellSettings
    });
    hotTable.loadData(createGridData());
    hotTable.render();
    isSyncingGrid = false;
  }

  function formatErrorField(field: string): string {
    if (field === 'participants') {
      return 'Teilnehmer';
    }

    const nameMatch = /^participants\.(\d+)\.name$/.exec(field);

    if (nameMatch) {
      return `Zeile ${Number(nameMatch[1]) + 1}, Teilnehmer`;
    }

    const pointsMatch = /^participants\.(\d+)\.pointsByTask\.(\d+)$/.exec(field);

    if (pointsMatch) {
      const row = Number(pointsMatch[1]) + 1;
      const taskIndex = Number(pointsMatch[2]);
      const taskName = tasks[taskIndex]?.name.trim() || `Aufgabe ${taskIndex + 1}`;

      return `Zeile ${row}, ${taskName}`;
    }

    return field;
  }

  function collectValidationMessages(fieldErrors: FieldErrors): string[] {
    return Object.entries(fieldErrors).flatMap(([field, messages]) =>
      messages.map((message) => `${formatErrorField(field)}: ${message}`)
    );
  }

  onMount(() => {
    if (!gridElement) {
      return;
    }

    hotTable = new Handsontable(gridElement, {
      data: createGridData(),
      colHeaders: createColumnHeaders(),
      columns: createColumns(),
      rowHeaders: true,
      height: 'auto',
      stretchH: 'all',
      autoWrapRow: true,
      autoWrapCol: true,
      contextMenu: ['remove_row', 'undo', 'redo'],
      manualColumnResize: true,
      manualRowResize: true,
      themeName: 'ht-theme-main',
      licenseKey: 'non-commercial-and-evaluation',
      cells: createCellSettings,
      afterChange(changes, source) {
        if (!changes || source === 'loadData') {
          return;
        }

        syncFromGrid();
      },
      afterRemoveRow() {
        syncFromGrid();
      }
    });

    return () => {
      hotTable?.destroy();
      hotTable = null;
    };
  });
</script>

<div class="space-y-6">
  <div class="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
    <div>
      <h3 class="text-sm font-semibold text-slate-900">Teilnehmer und Punkte</h3>
      <p class="mt-1 text-sm text-slate-600">
        Erfasse pro Zeile eine Person und die erreichten Punkte je Aufgabe.
      </p>
    </div>

    <button class="button-secondary" type="button" onclick={addParticipant}>Teilnehmer hinzufügen</button>
  </div>

  <div class="teilnehmer-hot overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
    <div bind:this={gridElement}></div>
  </div>

  {#if showErrors && validationMessages.length}
    <div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3">
      <h3 class="text-sm font-semibold text-red-800">Validierungsfehler</h3>
      <ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-red-700">
        {#each validationMessages as message}
          <li>{message}</li>
        {/each}
      </ul>
    </div>
  {/if}
</div>

<style>
  .teilnehmer-hot :global(.handsontable td.teilnehmer-grid-error) {
    background-color: #fef2f2 !important;
    color: #991b1b;
  }

  .teilnehmer-hot :global(.handsontable td.teilnehmer-grid-error.current),
  .teilnehmer-hot :global(.handsontable td.teilnehmer-grid-error.area),
  .teilnehmer-hot :global(.handsontable td.teilnehmer-grid-error.highlight) {
    background-color: #fee2e2 !important;
  }
</style>

// src/app/features/wizard/steps/teilnehmer-step/teilnehmer-step.component.ts
import { AfterViewInit, Component, ElementRef, OnDestroy, ViewChild, effect, inject } from '@angular/core';
import Handsontable from 'handsontable/base';
import type { CellProperties } from 'handsontable/settings';
import { registerAllModules } from 'handsontable/registry';
import type { ExamParticipant, FieldErrors } from '../../../../core/wizard.models';
import { WizardService } from '../../../../core/wizard.service';

registerAllModules();

@Component({
  selector: 'app-teilnehmer-step',
  standalone: true,
  templateUrl: './teilnehmer-step.component.html',
  styleUrl: './teilnehmer-step.component.css'
})
export class TeilnehmerStepComponent implements AfterViewInit, OnDestroy {
  @ViewChild('gridElement') private gridElement: ElementRef<HTMLDivElement> | undefined;

  protected readonly wizard = inject(WizardService);
  private hotTable: Handsontable | null = null;
  private isSyncingGrid = false;

  private readonly gridEffect = effect(() => {
    const state = this.wizard.state();

    JSON.stringify({
      tasks: state.data.aufgaben.tasks,
      participants: state.data.teilnehmer.participants,
      errors: state.validation.errorsByStep.teilnehmer,
      showErrors: Boolean(state.steps.find((item) => item.id === 'teilnehmer')?.touched)
    });

    if (this.hotTable) {
      this.updateGrid();
    }
  });

  protected get tasks() {
    return this.wizard.state().data.aufgaben.tasks;
  }

  protected get participants() {
    return this.wizard.state().data.teilnehmer.participants;
  }

  protected get errors() {
    return this.wizard.state().validation.errorsByStep.teilnehmer;
  }

  protected get showErrors(): boolean {
    return Boolean(this.wizard.state().steps.find((item) => item.id === 'teilnehmer')?.touched);
  }

  protected get validationMessages(): string[] {
    return this.collectValidationMessages(this.errors);
  }

  ngAfterViewInit(): void {
    if (!this.gridElement) {
      return;
    }

    this.hotTable = new Handsontable(this.gridElement.nativeElement, {
      data: this.createGridData(),
      colHeaders: this.createColumnHeaders(),
      columns: this.createColumns(),
      rowHeaders: true,
      height: 'auto',
      stretchH: 'all',
      autoWrapRow: true,
      autoWrapCol: true,
      contextMenu: ['remove_row', 'undo', 'redo'],
      manualColumnResize: true,
      manualRowResize: true,
      themeName: 'ht-theme-main',
      licenseKey: 'non-commercial-and-evaluation',
      cells: (row, column) => this.createCellSettings(row, column),
      afterChange: (changes, source) => {
        if (!changes || source === 'loadData') {
          return;
        }

        this.syncFromGrid();
      },
      afterRemoveRow: () => {
        this.syncFromGrid();
      }
    });
  }

  ngOnDestroy(): void {
    this.gridEffect.destroy();
    this.hotTable?.destroy();
    this.hotTable = null;
  }

  createParticipant(index = this.participants.length): ExamParticipant {
    return {
      name: `Teilnehmer ${index + 1}`,
      pointsByTask: this.tasks.map(() => 0)
    };
  }

  createGridData(): (string | number | null)[][] {
    const rows = this.participants.map((participant) => [
      participant.name,
      ...this.tasks.map((_, taskIndex) => participant.pointsByTask[taskIndex] ?? 0)
    ]);

    if (rows.length === 0) {
      const participant = this.createParticipant(0);

      return [[participant.name, ...participant.pointsByTask]];
    }

    return rows;
  }

  createColumnHeaders(): string[] {
    return [
      'Teilnehmer',
      ...this.tasks.map((task, index) => {
        const name = task.name.trim() || `Aufgabe ${index + 1}`;
        const maxPoints = task.maxPoints ?? 0;

        return `${name} (${maxPoints} P.)`;
      })
    ];
  }

  createColumns(): Handsontable.ColumnSettings[] {
    return [
      {
        type: 'text'
      },
      ...this.tasks.map(() => ({
        type: 'numeric',
        allowInvalid: true
      }))
    ];
  }

  normalizeText(value: unknown): string {
    if (typeof value === 'string') {
      return value;
    }

    if (value === null || value === undefined) {
      return '';
    }

    return String(value);
  }

  normalizePoints(value: unknown): number | null {
    if (value === null || value === undefined || value === '') {
      return null;
    }

    if (typeof value === 'number') {
      return Number.isFinite(value) ? value : null;
    }

    const normalized = String(value).trim().replace(',', '.');

    if (!normalized) {
      return null;
    }

    const parsed = Number(normalized);

    return Number.isFinite(parsed) ? parsed : null;
  }

  readGridParticipants(): ExamParticipant[] {
    if (!this.hotTable) {
      return [];
    }

    return this.hotTable
      .getData()
      .map((row) => ({
        name: this.normalizeText(row[0]).trim(),
        pointsByTask: this.tasks.map((_, taskIndex) => this.normalizePoints(row[taskIndex + 1]))
      }))
      .filter(
        (participant) =>
          participant.name.length > 0 || participant.pointsByTask.some((points) => points !== null)
      );
  }

  syncFromGrid(): void {
    if (!this.hotTable || this.isSyncingGrid) {
      return;
    }

    const nextParticipants = this.readGridParticipants();

    this.wizard.updateData((current) => ({
      ...current,
      teilnehmer: {
        participants: nextParticipants.length > 0 ? nextParticipants : [this.createParticipant(0)]
      }
    }));
    this.wizard.markCurrentTouched();
  }

  addParticipant(): void {
    this.wizard.updateData((current) => ({
      ...current,
      teilnehmer: {
        participants: [
          ...current.teilnehmer.participants,
          {
            name: `Teilnehmer ${current.teilnehmer.participants.length + 1}`,
            pointsByTask: current.aufgaben.tasks.map(() => 0)
          }
        ]
      }
    }));
    this.wizard.markCurrentTouched();
  }

  hasCellError(row: number, column: number): boolean {
    if (!this.showErrors) {
      return false;
    }

    if (this.participants.length === 0) {
      return row === 0 && column === 0 && Boolean(this.errors['participants']?.length);
    }

    if (!this.participants[row]) {
      return false;
    }

    const field =
      column === 0 ? `participants.${row}.name` : `participants.${row}.pointsByTask.${column - 1}`;

    return Boolean(this.errors[field]?.length);
  }

  createCellSettings(row: number, column: number): Partial<CellProperties> {
    return {
      className: this.hasCellError(row, column) ? 'teilnehmer-grid-error' : ''
    };
  }

  updateGrid(): void {
    if (!this.hotTable) {
      return;
    }

    this.isSyncingGrid = true;
    this.hotTable.updateSettings({
      colHeaders: this.createColumnHeaders(),
      columns: this.createColumns(),
      cells: (row, column) => this.createCellSettings(row, column)
    });
    this.hotTable.loadData(this.createGridData());
    this.hotTable.render();
    this.isSyncingGrid = false;
  }

  formatErrorField(field: string): string {
    if (field === 'participants') {
      return 'Teilnehmer';
    }

    const nameMatch = /^participants\.(\d+)\.name$/.exec(field);

    if (nameMatch) {
      return `Zeile ${Number(nameMatch[1]) + 1}, Teilnehmer`;
    }

    const pointsMatch = /^participants\.(\d+)\.pointsByTask\.(\d+)$/.exec(field);

    if (pointsMatch) {
      const row = Number(pointsMatch[1]) + 1;
      const taskIndex = Number(pointsMatch[2]);
      const taskName = this.tasks[taskIndex]?.name.trim() || `Aufgabe ${taskIndex + 1}`;

      return `Zeile ${row}, ${taskName}`;
    }

    return field;
  }

  collectValidationMessages(fieldErrors: FieldErrors): string[] {
    return Object.entries(fieldErrors).flatMap(([field, messages]) =>
      messages.map((message) => `${this.formatErrorField(field)}: ${message}`)
    );
  }
}

<div class="space-y-6">
  <div class="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
    <div>
      <h3 class="text-sm font-semibold text-slate-900">Teilnehmer und Punkte</h3>
      <p class="mt-1 text-sm text-slate-600">
        Erfasse pro Zeile eine Person und die erreichten Punkte je Aufgabe.
      </p>
    </div>

    <button class="button-secondary" type="button" (click)="addParticipant()">Teilnehmer hinzufügen</button>
  </div>

  <div class="teilnehmer-hot overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">
    <div #gridElement></div>
  </div>

  @if (showErrors && validationMessages.length) {
    <div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3">
      <h3 class="text-sm font-semibold text-red-800">Validierungsfehler</h3>
      <ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-red-700">
        @for (message of validationMessages; track message) {
          <li>{{ message }}</li>
        }
      </ul>
    </div>
  }
</div>
