// src/lib/steps/BasisStep.svelte
<script lang="ts">
  import FieldError from '../components/FieldError.svelte';
  import { wizard } from '../store/wizardStore';
  import type { WizardData } from '../types';

  $: data = $wizard.data.basis;
  $: step = $wizard.steps.find((item) => item.id === 'basis');
  $: errors = $wizard.validation.errorsByStep.basis;
  $: showErrors = Boolean(step?.touched);

  function textValue(event: Event): string {
    return (event.currentTarget as HTMLInputElement).value;
  }

  function updateBasis<K extends keyof WizardData['basis']>(key: K, value: WizardData['basis'][K]): void {
    wizard.updateData((current) => ({
      ...current,
      basis: {
        ...current.basis,
        [key]: value
      }
    }));
  }
</script>

<div class="field-grid">
  <label>
    <span class="field-label">Kurs</span>
    <input
      class={`field-input ${showErrors && errors.course ? 'field-input-error' : ''}`}
      type="text"
      value={data.course}
      oninput={(event) => updateBasis('course', textValue(event))}
      onblur={wizard.markCurrentTouched}
    />
    <FieldError errors={showErrors ? errors.course : undefined} />
  </label>

  <label>
    <span class="field-label">Thema</span>
    <input
      class={`field-input ${showErrors && errors.topic ? 'field-input-error' : ''}`}
      type="text"
      value={data.topic}
      oninput={(event) => updateBasis('topic', textValue(event))}
      onblur={wizard.markCurrentTouched}
    />
    <FieldError errors={showErrors ? errors.topic : undefined} />
  </label>
</div>

// src/app/features/wizard/steps/basis-step/basis-step.component.ts
import { Component, inject } from '@angular/core';
import type { WizardData } from '../../../../core/wizard.models';
import { WizardService } from '../../../../core/wizard.service';
import { FieldErrorComponent } from '../../../../shared/field-error/field-error.component';

@Component({
  selector: 'app-basis-step',
  standalone: true,
  imports: [FieldErrorComponent],
  templateUrl: './basis-step.component.html'
})
export class BasisStepComponent {
  protected readonly wizard = inject(WizardService);
  protected readonly state = this.wizard.state;

  protected get data(): WizardData['basis'] {
    return this.state().data.basis;
  }

  protected get errors() {
    return this.state().validation.errorsByStep.basis;
  }

  protected get showErrors(): boolean {
    return Boolean(this.state().steps.find((item) => item.id === 'basis')?.touched);
  }

  textValue(event: Event): string {
    return (event.currentTarget as HTMLInputElement).value;
  }

  updateBasis<K extends keyof WizardData['basis']>(key: K, value: WizardData['basis'][K]): void {
    this.wizard.updateData((current) => ({
      ...current,
      basis: {
        ...current.basis,
        [key]: value
      }
    }));
  }
}

<div class="field-grid">
  <label>
    <span class="field-label">Kurs</span>
    <input
      class="field-input"
      [class.field-input-error]="showErrors && errors['course']"
      type="text"
      [value]="data.course"
      (input)="updateBasis('course', textValue($event))"
      (blur)="wizard.markCurrentTouched()"
    />
    <app-field-error [errors]="showErrors ? errors['course'] : undefined" />
  </label>

  <label>
    <span class="field-label">Thema</span>
    <input
      class="field-input"
      [class.field-input-error]="showErrors && errors['topic']"
      type="text"
      [value]="data.topic"
      (input)="updateBasis('topic', textValue($event))"
      (blur)="wizard.markCurrentTouched()"
    />
    <app-field-error [errors]="showErrors ? errors['topic'] : undefined" />
  </label>
</div>
