// src/app/features/wizard/components/session-actions/session-actions.component.ts
import { Component, ElementRef, HostListener, ViewChild, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  createWizardSessionExport,
  createWizardSessionFilename,
  listWizardSessions,
  loadWizardSession,
  parseWizardSessionJson,
  saveWizardSession,
  type StoredWizardSession
} from '../../../../core/wizard-session-storage';
import { WizardService } from '../../../../core/wizard.service';

type ModalType = 'save' | 'load' | null;

@Component({
  selector: 'app-session-actions',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './session-actions.component.html'
})
export class SessionActionsComponent {
  private readonly wizardService = inject(WizardService);

  @ViewChild('fileInput') private fileInput: ElementRef<HTMLInputElement> | undefined;
  @ViewChild('sessionNameInput') private sessionNameInput: ElementRef<HTMLInputElement> | undefined;
  @ViewChild('selectedSessionSelect') private selectedSessionSelect: ElementRef<HTMLSelectElement> | undefined;
  @ViewChild('menuElement') private menuElement: ElementRef<HTMLDivElement> | undefined;

  protected readonly wizard = this.wizardService.state;
  protected menuOpen = false;
  protected activeModal: ModalType = null;
  protected sessionName = '';
  protected selectedSessionName = '';
  protected sessions: StoredWizardSession[] = [];
  protected fileError = '';

  protected get canSave(): boolean {
    return this.sessionName.trim().length > 0;
  }

  protected get canLoad(): boolean {
    return this.selectedSessionName.trim().length > 0;
  }

  @HostListener('document:click', ['$event'])
  handleDocumentClick(event: MouseEvent): void {
    const target = event.target;

    if (!(target instanceof Node)) {
      return;
    }

    if (!this.menuElement?.nativeElement.contains(target)) {
      this.closeMenus();
    }
  }

  @HostListener('document:keydown.escape')
  handleDocumentEscape(): void {
    if (this.activeModal) {
      this.closeModal();
      return;
    }

    if (this.fileError) {
      this.closeFileError();
      return;
    }

    this.closeMenus();
  }

  refreshSessions(): void {
    this.sessions = listWizardSessions();
  }

  closeMenus(): void {
    this.menuOpen = false;
  }

  closeModal(): void {
    this.activeModal = null;
  }

  closeFileError(): void {
    this.fileError = '';
  }

  createDefaultSessionName(): string {
    return [this.wizard().data.basis.course.trim(), this.wizard().data.basis.topic.trim()]
      .filter((value) => value.length > 0)
      .join(' ');
  }

  openSaveModal(): void {
    this.closeMenus();
    this.refreshSessions();
    this.sessionName = this.createDefaultSessionName();
    this.activeModal = 'save';
    window.setTimeout(() => this.sessionNameInput?.nativeElement.focus());
  }

  openLoadModal(): void {
    this.closeMenus();
    this.refreshSessions();
    this.selectedSessionName = this.sessions[0]?.name ?? '';
    this.activeModal = 'load';
    window.setTimeout(() => this.selectedSessionSelect?.nativeElement.focus());
  }

  saveSession(): void {
    if (!this.canSave) {
      return;
    }

    saveWizardSession(this.sessionName, this.wizard());
    this.refreshSessions();
    this.closeModal();
  }

  loadSession(): void {
    if (!this.canLoad) {
      return;
    }

    const snapshot = loadWizardSession(this.selectedSessionName);

    if (!snapshot) {
      this.refreshSessions();
      this.selectedSessionName = this.sessions[0]?.name ?? '';
      return;
    }

    this.wizardService.replaceSession(snapshot);
    this.closeModal();
  }

  openFileImport(): void {
    this.closeMenus();
    this.fileInput?.nativeElement.click();
  }

  async importFile(event: Event): Promise<void> {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];

    if (!file) {
      return;
    }

    try {
      const content = await file.text();
      const snapshot = parseWizardSessionJson(content);

      this.wizardService.replaceSession(snapshot);
    } catch (error) {
      this.fileError = error instanceof Error ? error.message : 'Die Datei konnte nicht importiert werden.';
    } finally {
      input.value = '';
    }
  }

  exportFile(): void {
    this.closeMenus();

    const payload = createWizardSessionExport(this.wizard());
    const blob = new Blob([JSON.stringify(payload, null, 2)], {
      type: 'application/json'
    });
    const url = URL.createObjectURL(blob);
    const downloadLink = document.createElement('a');

    downloadLink.href = url;
    downloadLink.download = createWizardSessionFilename(this.wizard().data.basis.course, this.wizard().data.basis.topic);
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);
    URL.revokeObjectURL(url);
  }

  formatSavedAt(value: string): string {
    return new Intl.DateTimeFormat('de-DE', {
      dateStyle: 'medium',
      timeStyle: 'short'
    }).format(new Date(value));
  }

  closeModalOnBackdrop(event: MouseEvent): void {
    if (event.target === event.currentTarget) {
      this.closeModal();
    }
  }

  closeFileErrorOnBackdrop(event: MouseEvent): void {
    if (event.target === event.currentTarget) {
      this.closeFileError();
    }
  }
}

<div class="relative" #menuElement>
  <button
    class="inline-flex h-10 w-10 items-center justify-center rounded-md border border-slate-300 bg-white text-slate-800 shadow-sm transition hover:border-slate-400 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-950/20"
    type="button"
    aria-label="Aktionen"
    aria-haspopup="menu"
    [attr.aria-expanded]="menuOpen"
    (click)="menuOpen = !menuOpen"
  >
    <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M4.75 6.75h14.5" />
      <path stroke-linecap="round" stroke-linejoin="round" d="M4.75 12h14.5" />
      <path stroke-linecap="round" stroke-linejoin="round" d="M4.75 17.25h14.5" />
    </svg>
  </button>

  @if (menuOpen) {
    <div
      class="absolute right-0 z-30 mt-2 w-52 overflow-hidden rounded-md border border-slate-200 bg-white py-1 text-sm shadow-lg"
      role="menu"
    >
      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        (click)="openLoadModal()"
      >
        Lade Session
      </button>

      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        (click)="openFileImport()"
      >
        Importiere Datei
      </button>

      <div class="my-1 border-t border-slate-100"></div>

      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        (click)="openSaveModal()"
      >
        Speichere Session
      </button>

      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        (click)="exportFile()"
      >
        Exportiere Datei
      </button>
    </div>
  }
</div>

<input #fileInput class="hidden" type="file" accept="application/json,.json" (change)="importFile($event)" />

@if (activeModal === 'save') {
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4"
    role="presentation"
    (click)="closeModalOnBackdrop($event)"
  >
    <div
      class="w-full max-w-md rounded-lg border border-slate-200 bg-white p-5 shadow-xl"
      role="dialog"
      aria-modal="true"
      aria-labelledby="save-session-title"
    >
      <form
        (submit)="
          $event.preventDefault();
          saveSession()
        "
      >
        <h2 id="save-session-title" class="text-lg font-semibold text-slate-950">Session speichern</h2>
        <p class="mt-2 text-sm text-slate-600">Gib einen Namen an, unter dem die aktuelle Session gespeichert wird.</p>

        <label class="mt-5 block">
          <span class="field-label">Session-Name</span>
          <input #sessionNameInput class="field-input" type="text" [(ngModel)]="sessionName" name="sessionName" list="saved-session-names" />
        </label>

        <datalist id="saved-session-names">
          @for (session of sessions; track session.name) {
            <option [value]="session.name">{{ session.name }}</option>
          }
        </datalist>

        <div class="mt-6 flex justify-end gap-2">
          <button class="button-secondary" type="button" (click)="closeModal()">Abbrechen</button>
          <button class="button-primary" type="submit" [disabled]="!canSave">Speichern</button>
        </div>
      </form>
    </div>
  </div>
}

@if (activeModal === 'load') {
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4"
    role="presentation"
    (click)="closeModalOnBackdrop($event)"
  >
    <div
      class="w-full max-w-md rounded-lg border border-slate-200 bg-white p-5 shadow-xl"
      role="dialog"
      aria-modal="true"
      aria-labelledby="load-session-title"
    >
      <form
        (submit)="
          $event.preventDefault();
          loadSession()
        "
      >
        <h2 id="load-session-title" class="text-lg font-semibold text-slate-950">Session laden</h2>

        @if (sessions.length) {
          <label class="mt-5 block">
            <span class="field-label">Gespeicherte Session</span>
            <select #selectedSessionSelect class="field-input" [(ngModel)]="selectedSessionName" name="selectedSessionName">
              @for (session of sessions; track session.name) {
                <option [value]="session.name">{{ session.name }} · {{ formatSavedAt(session.savedAt) }}</option>
              }
            </select>
          </label>
        } @else {
          <p class="mt-4 rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-600">
            Es sind noch keine Sessions gespeichert.
          </p>
        }

        <div class="mt-6 flex justify-end gap-2">
          <button class="button-secondary" type="button" (click)="closeModal()">Abbrechen</button>
          <button class="button-primary" type="submit" [disabled]="!canLoad">Laden</button>
        </div>
      </form>
    </div>
  </div>
}

@if (fileError) {
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4"
    role="presentation"
    (click)="closeFileErrorOnBackdrop($event)"
  >
    <div
      class="w-full max-w-md rounded-lg border border-red-200 bg-white p-5 shadow-xl"
      role="alertdialog"
      aria-modal="true"
      aria-labelledby="file-error-title"
    >
      <h2 id="file-error-title" class="text-lg font-semibold text-red-800">Import nicht möglich</h2>
      <p class="mt-2 text-sm text-slate-700">{{ fileError }}</p>

      <div class="mt-6 flex justify-end">
        <button class="button-primary" type="button" (click)="closeFileError()">Schließen</button>
      </div>
    </div>
  </div>
}

// src/lib/components/SessionActions.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import {
    createWizardSessionExport,
    createWizardSessionFilename,
    listWizardSessions,
    loadWizardSession,
    parseWizardSessionJson,
    saveWizardSession
  } from '../sessionStorage';
  import type { StoredWizardSession } from '../sessionStorage';
  import { wizard } from '../store/wizardStore';

  type ModalType = 'save' | 'load' | null;

  let menuOpen = false;
  let activeModal: ModalType = null;
  let sessionName = '';
  let selectedSessionName = '';
  let sessions: StoredWizardSession[] = [];
  let fileError = '';
  let fileInput: HTMLInputElement | null = null;
  let sessionNameInput: HTMLInputElement | null = null;
  let selectedSessionSelect: HTMLSelectElement | null = null;
  let menuElement: HTMLDivElement | null = null;

  $: canSave = sessionName.trim().length > 0;
  $: canLoad = selectedSessionName.trim().length > 0;

  function refreshSessions(): void {
    sessions = listWizardSessions();
  }

  function closeMenus(): void {
    menuOpen = false;
  }

  function closeModal(): void {
    activeModal = null;
  }

  function closeFileError(): void {
    fileError = '';
  }

  function createDefaultSessionName(): string {
    return [$wizard.data.basis.course.trim(), $wizard.data.basis.topic.trim()]
      .filter((value) => value.length > 0)
      .join(' ');
  }

  function handleWindowClick(event: MouseEvent): void {
    const target = event.target;

    if (!(target instanceof Node)) {
      return;
    }

    if (!menuElement?.contains(target)) {
      closeMenus();
    }
  }

  function handleWindowKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Escape') {
      return;
    }

    if (activeModal) {
      closeModal();
      return;
    }

    if (fileError) {
      closeFileError();
      return;
    }

    closeMenus();
  }

  async function openSaveModal(): Promise<void> {
    closeMenus();
    refreshSessions();
    sessionName = createDefaultSessionName();
    activeModal = 'save';
    await tick();
    sessionNameInput?.focus();
  }

  async function openLoadModal(): Promise<void> {
    closeMenus();
    refreshSessions();
    selectedSessionName = sessions[0]?.name ?? '';
    activeModal = 'load';
    await tick();
    selectedSessionSelect?.focus();
  }

  function saveSession(): void {
    if (!canSave) {
      return;
    }

    saveWizardSession(sessionName, $wizard);
    refreshSessions();
    closeModal();
  }

  function loadSession(): void {
    if (!canLoad) {
      return;
    }

    const snapshot = loadWizardSession(selectedSessionName);

    if (!snapshot) {
      refreshSessions();
      selectedSessionName = sessions[0]?.name ?? '';
      return;
    }

    wizard.replaceSession(snapshot);
    closeModal();
  }

  function openFileImport(): void {
    closeMenus();
    fileInput?.click();
  }

  async function importFile(event: Event): Promise<void> {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];

    if (!file) {
      return;
    }

    try {
      const content = await file.text();
      const snapshot = parseWizardSessionJson(content);

      wizard.replaceSession(snapshot);
    } catch (error) {
      fileError = error instanceof Error ? error.message : 'Die Datei konnte nicht importiert werden.';
    } finally {
      input.value = '';
    }
  }

  function exportFile(): void {
    closeMenus();

    const payload = createWizardSessionExport($wizard);
    const blob = new Blob([JSON.stringify(payload, null, 2)], {
      type: 'application/json'
    });
    const url = URL.createObjectURL(blob);
    const downloadLink = document.createElement('a');

    downloadLink.href = url;
    downloadLink.download = createWizardSessionFilename($wizard.data.basis.course, $wizard.data.basis.topic);
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);
    URL.revokeObjectURL(url);
  }

  function formatSavedAt(value: string): string {
    return new Intl.DateTimeFormat('de-DE', {
      dateStyle: 'medium',
      timeStyle: 'short'
    }).format(new Date(value));
  }

  function closeModalOnBackdrop(event: MouseEvent): void {
    if (event.target === event.currentTarget) {
      closeModal();
    }
  }

  function closeFileErrorOnBackdrop(event: MouseEvent): void {
    if (event.target === event.currentTarget) {
      closeFileError();
    }
  }
</script>

<svelte:window onclick={handleWindowClick} onkeydown={handleWindowKeydown} />

<div class="relative" bind:this={menuElement}>
  <button
    class="inline-flex h-10 w-10 items-center justify-center rounded-md border border-slate-300 bg-white text-slate-800 shadow-sm transition hover:border-slate-400 hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-950/20"
    type="button"
    aria-label="Aktionen"
    aria-haspopup="menu"
    aria-expanded={menuOpen}
    onclick={() => {
      menuOpen = !menuOpen;
    }}
  >
    <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" d="M4.75 6.75h14.5" />
      <path stroke-linecap="round" stroke-linejoin="round" d="M4.75 12h14.5" />
      <path stroke-linecap="round" stroke-linejoin="round" d="M4.75 17.25h14.5" />
    </svg>
  </button>

  {#if menuOpen}
    <div
      class="absolute right-0 z-30 mt-2 w-52 overflow-hidden rounded-md border border-slate-200 bg-white py-1 text-sm shadow-lg"
      role="menu"
    >
      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        onclick={openLoadModal}
      >
        Lade Session
      </button>

      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        onclick={openFileImport}
      >
        Importiere Datei
      </button>

      <div class="my-1 border-t border-slate-100"></div>

      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        onclick={openSaveModal}
      >
        Speichere Session
      </button>

      <button
        class="block w-full px-4 py-2 text-left text-slate-800 transition hover:bg-slate-50"
        type="button"
        role="menuitem"
        onclick={exportFile}
      >
        Exportiere Datei
      </button>
    </div>
  {/if}
</div>

<input class="hidden" type="file" accept="application/json,.json" bind:this={fileInput} onchange={importFile} />

{#if activeModal === 'save'}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4"
    role="presentation"
    onclick={closeModalOnBackdrop}
  >
    <div
      class="w-full max-w-md rounded-lg border border-slate-200 bg-white p-5 shadow-xl"
      role="dialog"
      aria-modal="true"
      aria-labelledby="save-session-title"
    >
      <form
        onsubmit={(event) => {
          event.preventDefault();
          saveSession();
        }}
      >
        <h2 id="save-session-title" class="text-lg font-semibold text-slate-950">Session speichern</h2>
        <p class="mt-2 text-sm text-slate-600">Gib einen Namen an, unter dem die aktuelle Session gespeichert wird.</p>

        <label class="mt-5 block">
          <span class="field-label">Session-Name</span>
          <input class="field-input" type="text" bind:value={sessionName} bind:this={sessionNameInput} list="saved-session-names" />
        </label>

        <datalist id="saved-session-names">
          {#each sessions as session}
            <option value={session.name}>{session.name}</option>
          {/each}
        </datalist>

        <div class="mt-6 flex justify-end gap-2">
          <button class="button-secondary" type="button" onclick={closeModal}>Abbrechen</button>
          <button class="button-primary" type="submit" disabled={!canSave}>Speichern</button>
        </div>
      </form>
    </div>
  </div>
{/if}

{#if activeModal === 'load'}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4"
    role="presentation"
    onclick={closeModalOnBackdrop}
  >
    <div
      class="w-full max-w-md rounded-lg border border-slate-200 bg-white p-5 shadow-xl"
      role="dialog"
      aria-modal="true"
      aria-labelledby="load-session-title"
    >
      <form
        onsubmit={(event) => {
          event.preventDefault();
          loadSession();
        }}
      >
        <h2 id="load-session-title" class="text-lg font-semibold text-slate-950">Session laden</h2>

        {#if sessions.length}
          <label class="mt-5 block">
            <span class="field-label">Gespeicherte Session</span>
            <select class="field-input" bind:value={selectedSessionName} bind:this={selectedSessionSelect}>
              {#each sessions as session}
                <option value={session.name}>{session.name} · {formatSavedAt(session.savedAt)}</option>
              {/each}
            </select>
          </label>
        {:else}
          <p class="mt-4 rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-600">
            Es sind noch keine Sessions gespeichert.
          </p>
        {/if}

        <div class="mt-6 flex justify-end gap-2">
          <button class="button-secondary" type="button" onclick={closeModal}>Abbrechen</button>
          <button class="button-primary" type="submit" disabled={!canLoad}>Laden</button>
        </div>
      </form>
    </div>
  </div>
{/if}

{#if fileError}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 px-4"
    role="presentation"
    onclick={closeFileErrorOnBackdrop}
  >
    <div
      class="w-full max-w-md rounded-lg border border-red-200 bg-white p-5 shadow-xl"
      role="alertdialog"
      aria-modal="true"
      aria-labelledby="file-error-title"
    >
      <h2 id="file-error-title" class="text-lg font-semibold text-red-800">Import nicht möglich</h2>
      <p class="mt-2 text-sm text-slate-700">{fileError}</p>

      <div class="mt-6 flex justify-end">
        <button class="button-primary" type="button" onclick={closeFileError}>Schließen</button>
      </div>
    </div>
  </div>
{/if}
