// src/app/features/wizard/components/wizard-shell/wizard-shell.component.ts
import { Component, inject } from '@angular/core';
import { WizardService } from '../../../../core/wizard.service';
import { AufgabenStepComponent } from '../../steps/aufgaben-step/aufgaben-step.component';
import { BasisStepComponent } from '../../steps/basis-step/basis-step.component';
import { JustierungStepComponent } from '../../steps/justierung-step/justierung-step.component';
import { NotenschemaStepComponent } from '../../steps/notenschema-step/notenschema-step.component';
import { TeilnehmerStepComponent } from '../../steps/teilnehmer-step/teilnehmer-step.component';
import { SessionActionsComponent } from '../session-actions/session-actions.component';
import { StepChainComponent } from '../step-chain/step-chain.component';
import { WizardNavigationComponent } from '../wizard-navigation/wizard-navigation.component';

@Component({
  selector: 'app-wizard-shell',
  standalone: true,
  imports: [
    AufgabenStepComponent,
    BasisStepComponent,
    JustierungStepComponent,
    NotenschemaStepComponent,
    TeilnehmerStepComponent,
    SessionActionsComponent,
    StepChainComponent,
    WizardNavigationComponent
  ],
  templateUrl: './wizard-shell.component.html'
})
export class WizardShellComponent {
  protected readonly wizard = inject(WizardService);
  protected readonly state = this.wizard.state;
  protected readonly currentStep = this.wizard.currentStep;
}

<div class="mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl flex-col gap-5 pb-36 md:pb-28">
  <header class="flex items-end justify-between gap-4">
    <div>
      <h1 class="text-3xl font-semibold tracking-tight text-slate-950">{{ state().title }}</h1>
    </div>

    <app-session-actions />
  </header>

  <section class="panel p-5">
    <app-step-chain />
  </section>

  <section class="panel flex-1 p-6">
    <div class="mb-6 border-b border-slate-200 pb-4">
      <p class="text-xs font-medium uppercase tracking-[0.18em] text-slate-500">
        Schritt {{ state().currentStepIndex + 1 }} von {{ state().steps.length }}
      </p>
      <h2 class="mt-1 text-xl font-semibold text-slate-950">{{ currentStep().title }}</h2>
    </div>

    @switch (currentStep().id) {
      @case ('basis') {
        <app-basis-step />
      }
      @case ('aufgaben') {
        <app-aufgaben-step />
      }
      @case ('notenschema') {
        <app-notenschema-step />
      }
      @case ('teilnehmer') {
        <app-teilnehmer-step />
      }
      @case ('justierung') {
        <app-justierung-step />
      }
    }
  </section>

  <app-wizard-navigation />
</div>

// src/lib/components/WizardShell.svelte
<script lang="ts">
  import { wizard } from '../store/wizardStore';
  import SessionActions from './SessionActions.svelte';
  import StepChain from './StepChain.svelte';
  import WizardNavigation from './WizardNavigation.svelte';

  $: state = $wizard;
  $: currentStep = state.steps[state.currentStepIndex];
</script>

<div class="mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl flex-col gap-5 pb-36 md:pb-28">
  <header class="flex items-end justify-between gap-4">
    <div>
      <h1 class="text-3xl font-semibold tracking-tight text-slate-950">{state.title}</h1>
    </div>

    <SessionActions />
  </header>

  <section class="panel p-5">
    <StepChain />
  </section>

  <section class="panel flex-1 p-6">
    <div class="mb-6 border-b border-slate-200 pb-4">
      <p class="text-xs font-medium uppercase tracking-[0.18em] text-slate-500">
        Schritt {state.currentStepIndex + 1} von {state.steps.length}
      </p>
      <h2 class="mt-1 text-xl font-semibold text-slate-950">{currentStep.title}</h2>
    </div>

    <svelte:component this={currentStep.view} />
  </section>

  <WizardNavigation />
</div>
